language: objective-c
matrix:
  include:
    - xcode_image: xcode7.3
    - xcode_image: xcode7.2
    - xcode_image: xcode7.1
    - xcode_image: xcode7.0
install:
  - brew install caskroom/cask/brew-cask
  - brew upgrade oclint
script: oclint -version

