language: generic
os: osx
before_install:
  - git clone --branch v0.28.0 https://github.com/creationix/nvm.git $HOME/.nvm && cd $HOME/.nvm || true
  - set +e; source $HOME/.nvm/nvm.sh; set -e
  - nvm install 4.1.1
install:
  - pwd
  - cd $TRAVIS_BUILD_DIR
  - pwd
  - find .
  - cd nodejs
  - npm install
  - cd ..
script: true
cache:
  - nodejs/node_modules
