language: objective-c
matrix:
  include:
    - osx_image: xcode7.2

install: true
script:
  - chmod +x ./nuke-cert.sh
  - ./nuke-cert.sh
  - security find-identity ~/Library/Keychains/login.keychain
  - security find-identity -v -p codesigning
