language: objective-c
osx_image: xcode7.2
install: true
script:
  - python --version
  - curl -sSL https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py
  - python /tmp/get-pip.py --user --no-wheel
  - virtualenv --version || true
  - pip --version || true
  - sleep 3
