language: generic
os: osx



install:
  # install brew cask
  - brew install caskroom/cask/brew-cask

  # install xamarin components
  - brew cask install xamarin xamarin-jdk xamarin-ios xamarin-studio

script:
  - true

