language: objective-c
osx_image: xcode7
before_install:
  - wget https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg --no-check-certificate
  - open ./googlechrome.dmg
  - sleep 3
script:
  - fastlane --version
  - sleep 3
