language: objective-c

osx_image: xcode8

env:
  - SIMULATOR="iPhone 5 (10.0)"
  - SIMULATOR="iPhone 5s (10.0)"
  - SIMULATOR="iPhone SE (10.0)"
  - SIMULATOR="iPhone 6 (10.0)"
  - SIMULATOR="iPhone 6 Plus (10.0)"
  - SIMULATOR="iPhone 6s (10.0)"
  - SIMULATOR="iPhone 6s Plus (10.0)"  

install: true

script:
  - set -o pipefail
  - export STRING_TO_MATCH="$SIMULATOR \["
  - echo "[ $STRING_TO_MATCH ]"
  - export IOS_SIMULATOR_UDID=`instruments -s devices | grep "$STRING_TO_MATCH"`
  - echo $IOS_SIMULATOR_UDID
