# Trigger
language: objective-c
osx_image: xcode7
script:
  - xcrun simctl list devices
  - xcrun simctl list devices | grep -v '^[-=]' | cut -d "(" -f2 | cut -d ")" -f1 | xargs -I {} xcrun simctl erase "{}"
  - xcrun simctl list devices
