language: objective-c
osx_image: xcode7
before_install:
  - gem list
  - gem update fastlane --verbose
  - gem list
  - sudo gem uninstall fastlane
  - sudo gem install fastlane -v 1.29.2
script:
  - fastlane --version
  - sleep 3
