language: objective-c
cache: cocoapods
matrix:
	include:
		- osx_image: xcode7.2
		  env: DEVICE="iPhone 6" OS_VERSION="9.2"
		- osx_image: xcode7.2
		  env: DEVICE="iPhone 5" OS_VERSION="8.3"
		- osx_image: beta-xcode6.3
		  env: DEVICE="iPhone 5" OS_VERSION="7.1.2"

install: true

script:
  - echo "platform=iOS Simulator,name=$DEVICE,OS=$OS_VERSION"
