language: objective-c
matrix:
  include:
    - osx_image: xcode7.3
    - osx_image: xcode7.2
    - osx_image: xcode7.1
    - osx_image: xcode7.0
install:
  - brew update
  - brew upgrade oclint
script: oclint -version
