language: objective-c
osx_image: xcode6.4

matrix:
  include:
    - osx_image: xcode6.4
    - osx_image: xcode7
    - osx_image: xcode7.1

install: true
script:
  - instruments -s devices
  - export IOS_SIMULATOR_UDID=`instruments -s devices | grep "iPhone 5s (8.4)" | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
  - echo $IOS_SIMULATOR_UDID

