language: objective-c
osx_image: xcode7.3

install: true

script:
  - wget https://ssl-download-crashlytics-com.s3.amazonaws.com/fabric/builds/Fabric-latest.zip
  - unzip Fabric-latest.zip
  - mv Fabric.app /Applications
