language: objective-c
osx_image: xcode7.3
rvm: 2.2.1

install:
  - bundle --version
  - pod --version || true
  - gem uninstall bundler -v 1.13.1
  - gem install bundler -v 1.12.5
  - bundle --version
script: pod --version
