# Trigger
language: objective-c
osx_image: xcode7
script:
  - gem list | grep xcodeproj
  - sudo gem update xcodeproj
  - gem list | grep xcodeproj
  - find /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0
