language: objective-c

matrix:
  include:
    - os: osx
    - osx_image: xcode8
    - osx_image: xcode7.3
    - osx_image: xcode7.2
    - osx_image: xcode7.1
    - osx_image: xcode7
    - osx_image: xcode6.4
    - osx_image: beta-xcode6.3
    - osx_image: beta-xcode6.2
    - osx_image: beta-xcode6.1
  
install: true

script:
  - bash --version
  - pod repo update
