language: objective-c
osx_image: xcode7.2

install: true

script:
  - curl -o tccmanager.py https://raw.githubusercontent.com/timsutton/scripts/master/tccmanager/tccmanager.py
  - chmod +x tccmanager.py
  - sudo ./tccmanager.py --allow com.kallisys.einstein
