language: objective-c
osx_image: xcode6.4
script:
  - instruments -s devices
  - instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -w "iPad 2 (8.4 Simulator)"
