# Trigger
language: objective-c
osx_image: beta-xcode6.3
script:
  - pod --version
  - sudo gem uninstall cocoapods
  - sudo gem install cocoapods -v 0.34.4
  - pod --version
  - gem uninstall cocoapods
  - gem install cocoapods -v 0.34.4
  - pod --version
