language: objective-c
osx_image: xcode8
git:
  depth: 3
before_install:
  - sudo gem uninstall bundler -v1.13
  - sudo gem install -n /usr/local/bin bundler -v 1.12
  - "echo -e \"machine github.com\\n login ragopor\\n password $CI_USER_PASSWORD\" >> ~/.netrc"
  - pod repo update --silent
  - gem install fastlane --no-rdoc --no-ri --no-document --quiet
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - pushd .
install: true
script:
  - popd
  - set -o pipefail
  - travis_retry fastlane --version
