language: objective-c
matrix:
  include:
    - osx_image: xcode7.2
    - osx_image: xcode7.1
    - osx_image: xcode7.0
before_install:
  - fastlane --version || true
  - gem update fastlane --no-document
  - fastlane --version || true
install: true
script: true
