language: objective-c
osx_image: xcode6.4

cache:
  directories:
    - ./nodejs

matrix:
  include:
    - osx_image: xcode6.4
    - osx_image: xcode7
    - osx_image: xcode7.1

install: sudo gem install sigh
script:
  - sigh manage

