language: objective-c

osx_image: xcode8

matrix:
  include:
    - osx_image: xcode8
    - osx_image: xcode7.3
    - osx_image: xcode7.2
    - osx_image: xcode7.1
    - osx_image: xcode7
    - osx_image: xcode6.4

install: true

script: 
  - cd ~/.cocoapods/repos/master
  - GIT_PAGER=cat git log -1
  - time pod setup
  - sleep 3
