language: objective-c
matrix:
  include:
    - osx_image: xcode7.2

install: true
script:
  - security find-certificate -a -c 'Apple Worldwide Developer Relations Certification Authority' -Z
  - sudo security find-certificate -a -c 'Apple Worldwide Developer Relations Certification Authority' -Z
