language: objective-c

osx_image: xcode8

env:
  - SIMULATOR="iPhone 5 (10.0)"
  - SIMULATOR="iPhone 5s (10.0)"
  - SIMULATOR="iPhone SE (10.0)"
  - SIMULATOR="iPhone 6 (10.0)"
  - SIMULATOR="iPhone 6 Plus (10.0)"
  - SIMULATOR="iPhone 6s (10.0)"
  - SIMULATOR="iPhone 6s Plus (10.0)"  

matrix:
  include:
    - osx_image: xcode8

install: true

script: 
  - export IOS_SIMULATOR_UDID=`instruments -s devices | grep "$SIMULATOR \[" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
  - echo $IOS_SIMULATOR_UDID
