language: objective-c
cache: cocoapods
matrix:
  include:
    - osx_image: xcode7.2

install: true

script:
  - pg_ctl -D /usr/local/var/postgres stop -s -m fast
  - pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start
