language: objective-c

osx_image: xcode8

env:
  - SIMULATOR_DEVICE="iPhone 5"

install: true

script:
  - set -o pipefail
  - export STRING_TO_MATCH="$SIMULATOR \("
  - echo "[ $STRING_TO_MATCH ]"
  - xcrun simctl list devices | grep "$SIMULATOR \("
  - xcrun simctl list devices | grep "$SIMULATOR \(" | awk -F '[ ]' '{print $1 $2 $3 $4}'
